name: Setup Node and build desktop app
description: Sets up Node, installs deps, and builds the desktop app
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Initialize source dependencies
      shell: bash
      run: git submodule update --init --recursive

    - name: Install dependencies
      shell: bash
      run: |
        npm ci --foreground-scripts

    - name: Build desktop application
      shell: bash
      run: |
        cd packages/desktop
        npm run build
