name: Setup Node and build desktop app
description: Sets up Node, installs deps, and builds the desktop app
inputs:
  tag:
    description: Git tag to check out (unused; kept for compatibility)
    required: false
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Build desktop application
      shell: bash
      run: |
        cd packages/desktop
        npm run build


