<script lang="ts">
  import { onMount, onDestroy, type Snippet } from "svelte";
  import { type ClientStateConfig } from "@sila/client";
  import ClientStateProvider from "@sila/client/comps/ClientStateProvider.svelte";
  import { ClientState } from "@sila/client";
  import { getRuntimeMode, readEnvForMode } from "@sila/core";
  import SpaceEntry from "./SpaceEntry.svelte";
  import SwinsContainer from "../swins/SwinsContainer.svelte";
  import ContextMenuHandler from "./ContextMenuHandler.svelte";
  import ThemeManager from "./themes/ThemeManager.svelte";
  import GlobalKeyHandlers from "./GlobalKeyHandlers.svelte";

  // ./lib/compiled-style.css should be generated by Tailwind; this import ensures styles are present
  import "@sila/client/compiled-style.css";
  import Toasts from "./ui/Toasts.svelte";
  import VertexViewerModal from "./vertex-viewer/VertexViewerModal.svelte";

  let {
    config,
    state,
    children,
  }: {
    config: ClientStateConfig | null;
    state?: ClientState;
    children?: Snippet;
  } = $props();

  const providedState = $derived(state || new ClientState());

  const runtimeMode = getRuntimeMode();

  const defaultTelemetryConfig = $derived.by(
    (): ClientStateConfig["telemetryConfig"] => {
      const apiKeyBase = "POSTHOG_API_KEY";
      const hostKeyBase = "POSTHOG_API_HOST";

      const apiKey = readEnvForMode(apiKeyBase, runtimeMode);
      const host = readEnvForMode(hostKeyBase, runtimeMode);

      if (!apiKey || !host) {
        console.error("Analytics not configured: missing env vars");
        return null;
      }

      return {
        apiKey,
        host,
        debug: runtimeMode === "development",
      };
    },
  );

  const resolvedConfig = $derived.by(() => {
    if (!config) return null;
    return {
      ...config,
      telemetryConfig: config.telemetryConfig ? config.telemetryConfig : defaultTelemetryConfig,
    };
  });

  $effect(() => {
    if (resolvedConfig) {
      providedState.init(resolvedConfig);
    }
  });

  onMount(() => {
    return () => {};
  });

  onDestroy(() => {
    providedState.cleanup();
  });

  console.log(
    "👋 Hey, if you see any bugs - please report them to https://github.com/silaorg/sila/issues",
  );
  console.log(
    "Reach out to the author of the project with any questions - Dmitry at d@dkury.com",
  );
</script>

{#if resolvedConfig}
  <ClientStateProvider instance={providedState}>
    <!-- Global key handlers -->
    <GlobalKeyHandlers />

    <!-- Set a current theme and a color scheme -->
    <ThemeManager />

    <!-- Where our spaces are rendered -->
    <SpaceEntry />

    <!-- Setup stacking windows (popover windows with navigation) we use for new conversations, settings, etc -->
    <SwinsContainer />

    <!-- Handle native and custom context menus -->
    <ContextMenuHandler />

    <!-- Setup toasts for notifications -->
    <Toasts />

    <!-- A modal for viewing vertices that reference files, such as images, videos, PDFs, etc -->
    <VertexViewerModal />

    <!-- Render whatever components passed from the wrappers of SilaApp (e.g Desktop, Mobile, etc)-->
    {@render children?.()}
  </ClientStateProvider>
{:else}
  Loading...
{/if}
