name: Build and Release (legacy - disabled)

# Triggers: Push to version tags (v1.0.0, v2.1.3, etc.) or manual dispatch
on:
  workflow_dispatch:

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is deprecated. Use 'Release - Create Draft', 'Release - Upload Win/Linux to Draft', and 'Release - Finalize (Publish)'."